import Head from "next/head";
import { ReactNode } from "react";

import NavBar from "./NavBar";
import Footer from "./Footer";

import { Box, Container } from "@chakra-ui/react";

type LayoutProps = { children?: ReactNode };

export default function Layout({ children }: LayoutProps) {
  return (
    <>
      <Head>
        <title>AIIRA Digital Twin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <main>
        <Box position={"relative"}>
          <Container maxW={"7xl"} minH={"md"} px={{ base: 10, sm: 8, lg: 16 }}>
            {children}
          </Container>
        </Box>
      </main>
      <Footer></Footer>
    </>
  );
}
