# Generated by Django 4.1.7 on 2023-07-25 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'datasets'), ('model', 'dataset')), models.Q(('app_label', 'software'), ('model', 'software')), models.Q(('app_label', 'software'), ('model', 'application')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name_plural': 'featured content',
            },
        ),
        migrations.AddIndex(
            model_name='featuredcontent',
            index=models.Index(fields=['content_type', 'object_id'], name='featured_fe_content_abe75f_idx'),
        ),
    ]
