# Generated by Django 4.1.7 on 2023-03-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('url', models.URLField(max_length=255)),
                ('application_type', models.CharField(choices=[('vice', 'CyVerse VICE app'), ('web', 'Web app')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('url', models.URLField(max_length=255)),
            ],
        ),
    ]
