# Generated by Django 4.1.7 on 2023-04-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='description_file',
            field=models.FileField(blank=True, upload_to='software/descriptions'),
        ),
        migrations.AddField(
            model_name='application',
            name='display_image',
            field=models.ImageField(blank=True, upload_to='software/images'),
        ),
        migrations.AddField(
            model_name='software',
            name='description_file',
            field=models.FileField(blank=True, upload_to='datasets/descriptions'),
        ),
        migrations.AddField(
            model_name='software',
            name='display_image',
            field=models.ImageField(blank=True, upload_to='software/images'),
        ),
    ]
